accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name='login'),
    # login
    path('logout', views.logout_view, name='logout'),
    # logout
    path('signup', views.signup_view, name='signup'),
    # registration / signup
    path('reset-password', views.reset_view, name='reset'),
    path('change-password', views.change_password, name='change'),
]

blog/urls.py
from django.urls import path
from blog.views import *     # * mean's the All function
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('test', test, name='test'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

from .views import timer_view

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    # re_path(r'^.*$', timer_view),
    path('admin/', admin.site.urls),
    # path ('url addres', 'view', #'name')
    # path('website/', include('website.urls'))
    path('', include('website.urls')),
    # path('blog\', include('blog.urls'))
    path('blog/', include('blog.urls')),
    #path('404', include('error.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
]
# static ('static','bace / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

class UserForm(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=100)

class ResetPasswordForm(models.Model):
    email = models.EmailField()

accounts/forms.py
from django import forms
from accounts.models import UserForm

class UserForm(forms.ModelForm):
    class Meta:
        model = UserForm
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm ,UserCreationForm
from django.contrib.auth.decorators import login_required
import random

from accounts.forms import UserForm
from django.contrib.auth.models import User

from django.conf import settings
from django.core.mail import EmailMessage , send_mail

from django.contrib import messages
import re

# Create your views here.
def login_view(request):
    '''
    if request.user.is_authenticated:
        msg = f'user is authenticated as {request.user.username}'
    else:
        msg = 'user is not authenticated'
    '''
    '''
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]
        user = User.objects.filter(email=email).first()
        if email:
            username = user.username
        user = authenticate(request, username=username , password=password)
        if user is not None:
            login(request, user)
            response = redirect('/') # redirect to main page
            return response
        else:
            pass
    form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)  #{'msg':msg}
    '''
    msg = None
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Check if the username is an email address
        if re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', username):
            email = username
            user = User.objects.filter(email=email).first()
            if user:
                username = user.username

            user = authenticate(request, username=username, password=password)
        else:
            user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            msg = messages.error(request, "User not found. Please try again.")
            

    form = AuthenticationForm()
    context = {'form': form, 'msg': msg}
    return render(request, 'accounts/login.html', context)
    '''
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')
        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else :
        return redirect('/')
'''
'''
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')
                if username:
                    user = authenticate(request, username=username, password=password)
                elif email:
                    user = authenticate(request, email=email, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')
        else:
            form = UserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')
'''
@login_required
def logout_view(request):
# if request.user.is_authenticated:
    logout(request)
    return redirect('/') # redirect to the main page

'''
def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                # return redirect('acconuts/login/')
                # return reverse('acconuts/login')
                return redirect('/accounts/login')
            
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html',context)
    else:
        return redirect('/')
'''


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                username = data['username']
                email = data['email']
                password = data['password']
                first_name = data['first_name']
                last_name = data['last_name']
                confirm = request.POST.get('confirm')

                
                if not User.objects.filter(email = email) and password == confirm :

                    user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                    user.save()
                    return redirect('/accounts/login')
                
                else :
                    msg = messages.warning(request, "passwords not match")
                    return render(request, 'accounts/signup.html',{'msg':msg})

        form = UserForm()
        return render(request, 'accounts/signup.html',{'form':form})
    else:
        return redirect('/')
    

'''
def reset_view(request) :
    if not request.user.is_authenticated:
        if request.method == 'POST':
            user_email = request.POST["email"]
            Email = request.POST["email"]
            Email = [str(Email)]
            number = random.randrange(10000000, 99999999)
            number = str(number)
            subject = 'reset password'
            message = 'Your Reset Password Code is : ' + number 
            email_from = settings.EMAIL_HOST_USER
            email = EmailMessage(subject, message, email_from, Email)
            email.send()
            send_mail(subject, message, email_from, Email)
            number = int(number)
            return redirect('/accounts/change-password')
        
        # if request.method == 'POST':
        #     password2 = request.POST["password"]
        #     confirm = request.POST["confirm"]
        #     if int(confirm) == number :

        #         u = User.objects.get(email=user_email)
        #         u.set_password(password2)
        #         u.save()


    return render(request, 'accounts/reset.html')

def change_password(request):
    if request.method == 'POST':
            password2 = request.POST["password"]
            confirm = request.POST["confirm"]
            if int(confirm) == number :

                u = User.objects.get(email=user_email)
                u.set_password(password2)
                u.save()
    return render(request, 'accounts/change.html')
'''
def reset_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            user_email = request.POST["email"]
            Email = request.POST["email"]
            Email = [str(Email)]
            number = random.randrange(10000000, 99999999)
            number = str(number)
            subject = 'reset password'
            message = 'Your Reset Password Code is : ' + number
            email_from = settings.EMAIL_HOST_USER
            email = EmailMessage(subject, message, email_from, Email)
            email.send()
            send_mail(subject, message, email_from, Email)
            
            request.session['user_email'] = user_email
            request.session['reset_code'] = number
            
            return redirect('/accounts/change-password')
    
    return render(request, 'accounts/reset.html')


def change_password(request):
    if request.method == 'POST':
        password2 = request.POST["password"]
        password2c = request.POST["password2"]
        confirm = request.POST["confirm"]
        if password2 == password2c:
            user_email = request.session.get('user_email')
            reset_code = request.session.get('reset_code')
            
            if str(password2) == str(password2c):
                if confirm == reset_code:
                    try:
                        user = User.objects.get(email=user_email)
                        user.set_password(password2)
                        user.save()
                        return redirect('/accounts/login')
                    except User.DoesNotExist:
                        return redirect('/accounts/reset-password')
            
    return render(request, 'accounts/change.html')

templates/accounts/change.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            text-align: center;
        }

        div {
            border: 3px solid black;
            border-radius: 10px;
            margin: 60px;
            padding: 20px;
            max-width: 20em;
            ;
        }
    </style>
</head>

<body>
    <div>
        <form action="#" method="post">
            {% csrf_token %}
            <div>
                <label>Your new password</label>
                <input type="password" name="password">
            </div>
            <div>
                <label>Confirm new password</label>
                <input type="password" name="password2">
            </div>
            <div>
                <label>Email Confirm Code</label>
                <input type="text" name="confirm">
            </div>
            <button type="submit" class="btn btn-primary btn-block submit-btn">Confirm</button>
        </form>
    </div>
</body>

</html>

templates/accounts/login.html
<!-- <p>{{msg}}</p>
{% if request.user.is_authenticated %}
<p>user is authenticated as {{request.user.username}}</p>
{% else %}
<p>user is not authenticated</p>
{% endif %} -->

{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Login Page</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4" style="font-size: 1.5em;">Sign In with username or email</h3>
                        <form method="post" action="{% url 'accounts:login' %}" class="login-form">
                            {% csrf_token %}

                            <!-- <div class="form-group">
                                <input type="text" name="username" class="form-control rounded-left"
                                    placeholder="Username" >
                            </div>

                            <div class="form-group">
                                <input type="email" name="email" class="form-control rounded-left"
                                    placeholder="email" >
                            </div> -->

                            <div class="form-group">
                                <input type="text" name="username" class="form-control rounded-left"
                                    placeholder="Email or Username" >
                            </div>

                            <div class="form-group d-flex">
                                <input type="password" name="password" class="form-control rounded-left"
                                    placeholder="Password" required>
                            </div>
                            <!-- {{form.as_p}} -->
                            <div class="form-group">
                                <button type="submit"
                                    class="form-control btn btn-primary rounded submit px-3">Login</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:reset' %}">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/accounts/reset.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bootstrap 5 Forgot Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="container d-flex flex-column">
      <div class="row align-items-center justify-content-center
          min-vh-100">
        <div class="col-12 col-md-8 col-lg-4">
          <div class="card shadow-sm">
            <div class="card-body">
              <div class="mb-4">
                <h5>Forgot Password?</h5>
                <p class="mb-2">Enter your registered email ID to reset the password
                </p>
              </div>
              <form method="post" action="{% url 'accounts:reset' %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  <input type="email" id="email" class="form-control" name="email" placeholder="Enter Your Email"
                    required="">
                </div>
                <div class="mb-3 d-grid">
                  <button type="submit" class="btn btn-primary">
                    Reset Password
                  </button>
                </div>
                <span>Don't have an account? <a href="{% url 'accounts:signup' %}">sign in</a></span>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

</html>

templates/accounts/signup.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Sign Up</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <!-- <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Sign Up Page</h2>
                </div> -->
            </div>
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Sign Up</h3>
                        <form method="post" action="{% url 'accounts:signup' %}" class="login-form">
                            {% csrf_token %}

                            <div class="form-group">
                                <input type="text" name="first_name" class="form-control rounded-left"
                                    placeholder="Fisrt Name" required> 
                            </div>

                            <div class="form-group">
                                <input type="text" name="last_name" class="form-control rounded-left"
                                    placeholder="Last Name" required> 
                            </div>

                            <div class="form-group">
                                <input type="text" name="username" class="form-control rounded-left"
                                    placeholder="Username" required> 
                            </div>

                            <div class="form-group">
                                <input type="text" name="email" class="form-control rounded-left"
                                    placeholder="Email Address" required> 
                            </div>

                            <div class="form-group d-flex">
                                <input type="password" name="password" class="form-control rounded-left"
                                    placeholder="Password" required> 
                            </div>
                            <div class="form-group d-flex">
                                <input type="password" name="confirm" class="form-control rounded-left"
                                    placeholder="Confirm Password" required> 
                            </div>

                            <div class="form-group">
                                <button type="submit"
                                    class="form-control btn btn-primary rounded submit px-3">sign-up</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:reset' %}">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>