blog/urls.py
from django.urls import path
from blog.views import *     # * mean's the All function
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('test', test, name='test'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

from .views import timer_view

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    # re_path(r'^.*$', timer_view),
    path('admin/', admin.site.urls),
    # path ('url addres', 'view', #'name')
    # path('website/', include('website.urls'))
    path('', include('website.urls')),
    # path('blog\', include('blog.urls'))
    path('blog/', include('blog.urls')),
    #path('404', include('error.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
]
# static ('static','bace / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *     # * mean's the All function

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('test', test_view, name='test'),
    path('newsletter', newsletter_view, name='newsletter'),
]
    

website/models.py
from django.db import models

# Create your models here.
class contact(models.Model) :
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta :
        ordering = ['-created_date']

    # def __str__ (self) :
    #     return '{} - {}'.format(self.name, self.id)

class Newsletter(models.Model):
    email = models.EmailField()

    def __str__ (self) :
        return self.email

website/forms.py
from django import forms
from website.models import contact, Newsletter
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.ModelForm) :
    # age = forms.IntegerField()
    captcha = CaptchaField()
    class Meta:
        model = contact
        fields = ['name', 'email', 'subject', 'message']
        # fields = '__all__'
        # fields = ['name', 'email'] or exclude = ['something'] and ...
        # widgets = ...

class NewsletterForm(forms.ModelForm) :
    class Meta :
        model = Newsletter
        fields = '__all__'

website/views.py
from django.shortcuts import render
import datetime
from django.http import HttpResponse, JsonResponse ,HttpResponseRedirect
from website.models import contact
from website.forms import NameForm, ContactForm , NewsletterForm
from django.contrib import messages
# Create your views here.


def http_test(request) :
    return HttpResponse ('<h1>Hello Django! This is the first http-test</h1>')

def json_test(request) :
    return JsonResponse ({'name' : 'Mohammad mahdi'})

def time(request) :
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

def index_view(request) :
    return render(request, 'website/index.html')

def about_view(request) :
    return render(request, 'website/about.html')

# def contact_view(request) :
#     return HttpResponse ('<h1>Contact</h1>')

def contact_view(request) :
    if request.method == 'POST' :
        form = ContactForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.name = 'Anonymous'
            obj.save()
            messages.add_message(request,messages.SUCCESS, 'Your ticket submited successfully')
        else :
            messages.add_message(request,messages.ERROR, 'Your ticket didnt submited')
    form = ContactForm()
    return render(request, 'website/contact.html', {'form':form})

def test_view(request) :
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data['name'] # for NameForm
            form.save()
            return HttpResponse('<h1>Done</h1>')
        else:
            return HttpResponse('Not_Valid') # if name on form is incorrect

    form = ContactForm()
    return render(request, 'website/test.html',{'form': form})

def newsletter_view(request) :
    if request.method == "POST" :
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

templates/website/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<!-- start banner Area -->
<section class="about-banner relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					About Us
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="about.html"> About Us</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 info-left">
				<img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="">
			</div>
			<div class="col-lg-6 info-right">
				<h6>About Us</h6>
				<h1>Who We Are?</h1>
				<p>
					Here, I focus on a range of items and features that we use in life without giving them a second
					thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
					incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
					ullamco.
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Other issues we can help you with</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Rent a Car</h4>
					</a>
					<p>
						The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Cruise Booking</h4>
					</a>
					<p>
						I was always somebody who felt quite sorry for myself, what I had not got compared.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>To Do List</h4>
					</a>
					<p>
						The following article covers a topic that has recently moved to center stage–at least it seems.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Food Features</h4>
					</a>
					<p>
						There are many kinds of narratives and organizing principles. Science is driven by evidence.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End other-issue Area -->
{% endblock %}

templates/website/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Contact Us
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="contact.html"> Contact Us</a>
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
	<div class="container">
		<div class="row">
			<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
			<div class="col-lg-4 d-flex flex-column address-wrap">
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-home"></span>
					</div>
					<div class="contact-details">
						<h5>Binghamton, New York</h5>
						<p>
							4343 Hinkle Deegan Lake Road
						</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-phone-handset"></span>
					</div>
					<div class="contact-details">
						<h5>00 (958) 9865 562</h5>
						<p>Mon to Fri 9am to 6 pm</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-envelope"></span>
					</div>
					<div class="contact-details">
						<h5>support@colorlib.com</h5>
						<p>Send us your query anytime!</p>
					</div>
				</div>
			</div>
			<div class="col-lg-8">
				<form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
					<div class="row">
						{% csrf_token %}
						<div class="col-lg-6 form-group">
							<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control"
								required="" type="text">

							<input name="email" placeholder="Enter email address"
								pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
								class="common-input mb-20 form-control" required="" type="email">

							<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control"
								 type="text">
						</div>
						<div class="col-lg-6 form-group">
							<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'"
								required=""></textarea>
						</div>
						<div class="col-lg-12">

							<div class="pb-3">
								{{form.captcha}}
							</div>

							<div class="alert-msg" style="text-align: left;"></div>
							<br/><button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>
						</div>
					</div>
				</form>
			</div>
			
<!-- End contact-page Area -->
{% endblock %}

templates/website/index.html
{% extends "base.html" %}
{% load static %}
{% load website-tag %}
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row fullscreen align-items-center justify-content-between">
			<div class="col-lg-6 col-md-6 banner-left">
				<h6 class="text-white">Away from monotonous life</h6>
				<h1 class="text-white">Magical Travel</h1>
				<p class="text-white">
					If you are looking at blank cassettes on the web, you may be very confused at the difference in
					price. You may see some for as low as $.17 each.
				</p>

			</div>

		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start popular-destination Area -->
<section class="popular-destination-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-8">
				<div class="title text-center">
					<h1 class="mb-10">Popular Destinations</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast,
						day.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$150</a>
						<h4>Mountain River</h4>
						<p>Paraguay</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$250</a>
						<h4>Dream City</h4>
						<p>Paris</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$350</a>
						<h4>Cloud Mountain</h4>
						<p>Sri Lanka</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End popular-destination Area -->


<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Other issues we can help you with</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Rent a Car</h4>
					</a>
					<p>
						The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Cruise Booking</h4>
					</a>
					<p>
						I was always somebody who felt quite sorry for myself, what I had not got compared.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>To Do List</h4>
					</a>
					<p>
						The following article covers a topic that has recently moved to center stage–at least it seems.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Food Features</h4>
					</a>
					<p>
						There are many kinds of narratives and organizing principles. Science is driven by evidence.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End other-issue Area -->





<!-- Start home-about Area -->
<section class="home-about-area">
	<div class="container-fluid">
		<div class="row align-items-center justify-content-end">
			<div class="col-lg-6 col-md-12 home-about-left">
				<h1>
					Did not find your Package? <br>
					Feel free to ask us. <br>
					We‘ll make it for you
				</h1>
				<p>
					inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct
					standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the
					job is beyond reproach. inappropriate behavior is often laughed.
				</p>
				<a href="#" class="primary-btn text-uppercase">request custom price</a>
			</div>
			<div class="col-lg-6 col-md-12 home-about-right no-padding">
				<img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="">
			</div>
		</div>
	</div>
</section>
<!-- End home-about Area -->


<!-- Start blog Area -->
<section class="recent-blog-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-60 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Latest from Our Blog</h1>
					<p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.
					</p>
				</div>
			</div>
		</div>
		{% lastpost %}
	</div>
</section>
<!-- End recent-blog Area -->

{% endblock %}

templates/website/last-post.html
{% load static %}

<div class="row">
    <div class="active-recent-blog-carusel">
        {% for post in posts %}
        <div class="single-recent-blog-post item">
            <div class="thumb">
                <img style="height: 205px; width: auto; margin-left: auto; margin-right: auto;"  class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <div class="tags">
                    
                    <ul>
                        {% for cat in post.category.all %}
                        <li>
                            <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    
                </div>
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h4 class="title">{{post.title}}</h4>
                </a>
                <p>
                    {{post.content|truncatewords:15}}
                </p>
                <h6 class="date">{{post.published_date|date:"Y/m/d"}}</h6>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/website/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test-view</title>
    <style>
        div{
            width: 300px;
            padding: 20px;
            border: 3px solid black;
            outline: 3px solid gray;
            border-radius: 20px;
            text-align: center;
            margin: auto;
            margin-top: 3em;
        }
        h2{
            text-align: center;
            margin-top: 30px;
            font-size: xx-large;
            text-shadow: 2px 2px 2px#ff0000;
        }
        button{
            color: green;
            font-family: cursive;
            border: 1px dotted green;
            border-radius: 2px;
        }
    </style>
</head>
<body>
    <h2>Test-Form</h2>
    <form action="{% url 'website:test' %}" method="post">
        {% csrf_token %}
        <div>
            <!-- <label for="">name: </label>
            <input type="text" name="name"><br><br>
            <label>email: </label>
            <input type="email" name="email"><br><br>
            <label>subject: </label>
            <input type="text" name="subject"><br><br>
            <label>message: </label>
            <input type="text" name="message"><br><br> -->
            {{ form.as_p }}
            <button type="submit">submit</button>
        </div>
    </form>
</body>
</html>