accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login_view, name='login'),
    # login
    path('logout', views.logout_view, name='logout'),
    # logout
    path('signup', views.signup_view, name='signup'),
    # registration / signup
    path('reset-password', views.reset_view, name='reset'),
    path('change-password', views.change_password, name='change'),
]

blog/urls.py
from django.urls import path
from blog.views import *     # * mean's the All function
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('test', test, name='test'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

from .views import timer_view

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    # re_path(r'^.*$', timer_view),
    path('admin/', admin.site.urls),
    # path ('url addres', 'view', #'name')
    # path('website/', include('website.urls'))
    path('', include('website.urls')),
    # path('blog\', include('blog.urls'))
    path('blog/', include('blog.urls')),
    #path('404', include('error.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
]
# static ('static','bace / static')
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *     # * mean's the All function

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('test', test_view, name='test'),
    path('newsletter', newsletter_view, name='newsletter'),
]
    

templates/base.html
{% load compress %}

{% load static %}

{% compress css %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
{% endcompress %}

<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul>
                            {% if request.user.is_authenticated %}
                            <li style="background-color: white; border-radius: 3px; color: black; padding: 5px;" >Loged in as {{request.user.username}}</li>
                            <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                        <div class="header-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'website:index' %}">Home</a></li>
                        <li><a href="{% url 'website:about' %}">About</a></li>
                        <li><a href="{% url 'blog:index' %}">Blog</a></li>

                        <li class="menu-has-children"><a href="">Pages</a>
                            <ul>
                                <li><a href="elements.html">Elements</a></li>
                                <li class="menu-has-children"><a href="">Level 2 </a>
                                    <ul>
                                        <li><a href="#">Item One</a></li>
                                        <li><a href="#">Item Two</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="{% url  'website:contact' %}">Contact</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header>

    {% block content %}

    {% endblock %}

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
    {% endif %}

    {% if form.errors %}
    <div class="alert alert-error">
        <h4>Please fix the following errors</h4>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
    </div>
    </div>
    </section>

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">

            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message. It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div>
                            <form action="{% url 'website:newsletter' %}" method="post" class="subscription relative">
                                {% csrf_token %}
                                <div class="input-group d-flex flex-row">
                                    <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn" type="submit"><span
                                            class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->
    {% load static %}

    {% compress js %}

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endcompress %}
</body>

</html>

templates/landing.html
<!DOCTYPE html>
<html>
<head>
    <title>صفحه در حال ساخت و بروزرسانی است</title>
    <style>
        body {
            background-color: #f4f4f4;
            font-family: Arial, sans-serif;
            text-align: center;
            padding-top: 150px;
            color: #333;
        }

        h1 {
            font-size: 36px;
            margin-bottom: 20px;
        }

        p {
            font-size: 18px;
            margin-bottom: 10px;
        }

        .underline {
            border-bottom: 2px solid #333;
            padding-bottom: 5px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <h1>سایت در حال ساخت و بروزرسانی است</h1>
    <p>به زودی با شما خواهیم بود.</p>
    <p class="underline">nik404e@gmail.com</p>
</body>
</html>

templates/popularposts.html
<ul>
    {% for post in posts %}
    <li>{{post.title}}</li>
    {% endfor %}
</ul>

templates/test.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            text-align: center;
            color: red;
            border: solid 5px blue;
            border-radius: 40px 0px 40px 0px ;
            padding: 5px;
        }
        body{
            margin: 30px;
        }
        p{
            font-size: large;
            font-family: 'Courier New', Courier, monospace;
        }
        pre{
            font-size: large;
            font-family: 'Courier New', Courier, monospace;
            color: brown;
        }
    </style>
</head>
<body>
    <h1>This is the test HTML</h1>
    <hr/>
    <p>The page loaded in -> {% function %}</p>
    <hr/>
    <p>Blog post Counter : {% total_post as tp %}{{tp}}</p>
    <hr/>
    <p style="font-size: 32px; color: deeppink;" >Posts: </p>
    {% posts as totalpost %}
    {% for post in totalpost %}
    <pre>   {{post.title}}</pre>
    <pre style="color: darkgreen;">       {{post.content|snippet:50}}</pre>
    {% endfor %}
    <hr/>

    {% latestposts %}
    
</body>
</html>